/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btth5_giatoc;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/**
 *
 * @author Reus
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        JDateChooser_Option();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jLabel = new javax.swing.JLabel();
        jLabel_MaTV = new javax.swing.JLabel();
        jTextField_MaTV = new javax.swing.JTextField();
        jLabel_HoTen = new javax.swing.JLabel();
        jTextField_HoTen = new javax.swing.JTextField();
        jLabel_GioiTinh = new javax.swing.JLabel();
        jComboBox_GT = new javax.swing.JComboBox();
        jComboBox_ChungToc = new javax.swing.JComboBox();
        jLabel_ChungToc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_NgheNghiep = new javax.swing.JComboBox();
        jLabel_NgaySinh = new javax.swing.JLabel();
        jDateChooser_NgaySinh = new com.toedter.calendar.JDateChooser();
        jButton_Nhap = new javax.swing.JButton();
        jLabel_Test = new javax.swing.JLabel();
        jLabel_LinhChi = new javax.swing.JLabel();
        jTextField_LinhChi = new javax.swing.JTextField();
        jLabel_HaThuO = new javax.swing.JLabel();
        jTextField_HaThuO = new javax.swing.JTextField();
        jLabel_NhanSam = new javax.swing.JLabel();
        jTextField_NhanSam = new javax.swing.JTextField();
        jLabel_ThatTamLien = new javax.swing.JLabel();
        jTextField_ThatTamLien = new javax.swing.JTextField();
        jLabel_BichNgoc = new javax.swing.JLabel();
        jTextField_BichNgoc = new javax.swing.JTextField();
        jLabel_LamNgoc = new javax.swing.JLabel();
        jTextField_LamNgoc = new javax.swing.JTextField();
        jLabel_HongNgoc = new javax.swing.JLabel();
        jTextField_HongNgoc = new javax.swing.JTextField();
        jLabel_KimCuong = new javax.swing.JLabel();
        jTextField_KimCuong = new javax.swing.JTextField();
        jLabel_SLCayThuoc = new javax.swing.JLabel();
        jTextField_SLCayThuoc = new javax.swing.JTextField();
        jLabel_AoGiap = new javax.swing.JLabel();
        jTextField_AoGiap = new javax.swing.JTextField();
        jLabel_DungCuSX = new javax.swing.JLabel();
        jTextField_DungCuSX = new javax.swing.JTextField();
        jTextField_VuKhi = new javax.swing.JTextField();
        jLabel_VuKhi = new javax.swing.JLabel();
        jLabel_Ho = new javax.swing.JLabel();
        jTextField_Ho = new javax.swing.JTextField();
        jTextField_Soi = new javax.swing.JTextField();
        jLabel_Soi = new javax.swing.JLabel();
        jTextField_Gau = new javax.swing.JTextField();
        jLabel_Gau = new javax.swing.JLabel();
        jLabel_SLChuyenXeBaoVe = new javax.swing.JLabel();
        jTextField_SLChuyenXeBaoVe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel_SLChuyenXeVanChuyen = new javax.swing.JLabel();
        jTextField_SLChuyenXeVanChuyen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel.setText("Nhập Danh Sách Thành Viên Gia Tộc");

        jLabel_MaTV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_MaTV.setText("Mã Thành Viên:");

        jTextField_MaTV.setName(""); // NOI18N
        jTextField_MaTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_MaTVMouseClicked(evt);
            }
        });
        jTextField_MaTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MaTVActionPerformed(evt);
            }
        });

        jLabel_HoTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_HoTen.setText("Họ Tên:");

        jTextField_HoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoTenMouseClicked(evt);
            }
        });

        jLabel_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_GioiTinh.setText("Giới Tính:");

        jComboBox_GT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        jComboBox_GT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_GTMouseClicked(evt);
            }
        });
        jComboBox_GT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_GTActionPerformed(evt);
            }
        });

        jComboBox_ChungToc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tinh Linh", "Địa Tinh", "Người" }));
        jComboBox_ChungToc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_ChungTocMouseClicked(evt);
            }
        });
        jComboBox_ChungToc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ChungTocItemStateChanged(evt);
            }
        });
        jComboBox_ChungToc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ChungTocActionPerformed(evt);
            }
        });

        jLabel_ChungToc.setText("Chủng Tộc:");

        jLabel1.setText("Nghề Nghiệp:");

        jComboBox_NgheNghiep.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tìm Thuốc", "Trồng Thuốc" }));
        jComboBox_NgheNghiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_NgheNghiepMouseClicked(evt);
            }
        });
        jComboBox_NgheNghiep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_NgheNghiepItemStateChanged(evt);
            }
        });
        jComboBox_NgheNghiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NgheNghiepActionPerformed(evt);
            }
        });

        jLabel_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_NgaySinh.setText("Ngày Sinh: ");

        jDateChooser_NgaySinh.setBackground(new java.awt.Color(153, 153, 255));
        jDateChooser_NgaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDateChooser_NgaySinh.setDateFormatString("dd- MM-yyyy");
        jDateChooser_NgaySinh.setDoubleBuffered(false);
        jDateChooser_NgaySinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser_NgaySinhMouseClicked(evt);
            }
        });

        jButton_Nhap.setText("Lưu Xuống CSDL");
        jButton_Nhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_NhapMouseClicked(evt);
            }
        });
        jButton_Nhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NhapActionPerformed(evt);
            }
        });

        jLabel_LinhChi.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_LinhChi.setText("Linh Chi:");

        jTextField_LinhChi.setForeground(new java.awt.Color(0, 0, 51));
        jTextField_LinhChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_HaThuO.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_HaThuO.setText("Hà Thủ Ô:");

        jTextField_HaThuO.setForeground(new java.awt.Color(0, 0, 51));
        jTextField_HaThuO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_NhanSam.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_NhanSam.setText("Nhân Sâm:");

        jTextField_NhanSam.setForeground(new java.awt.Color(0, 0, 51));
        jTextField_NhanSam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_ThatTamLien.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_ThatTamLien.setText("Thất Tâm Liên:");

        jTextField_ThatTamLien.setForeground(new java.awt.Color(0, 0, 51));
        jTextField_ThatTamLien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_BichNgoc.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_BichNgoc.setText("Bích Ngọc:");
        jLabel_BichNgoc.setEnabled(false);

        jTextField_BichNgoc.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_BichNgoc.setEnabled(false);
        jTextField_BichNgoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_LamNgoc.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_LamNgoc.setText("Lam Ngọc:");
        jLabel_LamNgoc.setEnabled(false);

        jTextField_LamNgoc.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_LamNgoc.setEnabled(false);
        jTextField_LamNgoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_HongNgoc.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_HongNgoc.setText("Hồng Ngọc:");
        jLabel_HongNgoc.setEnabled(false);

        jTextField_HongNgoc.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_HongNgoc.setEnabled(false);
        jTextField_HongNgoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_KimCuong.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_KimCuong.setText("Kim Cương:");
        jLabel_KimCuong.setEnabled(false);

        jTextField_KimCuong.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_KimCuong.setEnabled(false);
        jTextField_KimCuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });
        jTextField_KimCuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_KimCuongActionPerformed(evt);
            }
        });

        jLabel_SLCayThuoc.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_SLCayThuoc.setText("Số Lượng Cây Thuốc Trồng Được:");
        jLabel_SLCayThuoc.setEnabled(false);

        jTextField_SLCayThuoc.setEnabled(false);
        jTextField_SLCayThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_AoGiap.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_AoGiap.setText("Áo Giáp:");
        jLabel_AoGiap.setEnabled(false);

        jTextField_AoGiap.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_AoGiap.setEnabled(false);
        jTextField_AoGiap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_DungCuSX.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_DungCuSX.setText("Dụng Cụ SX:");
        jLabel_DungCuSX.setEnabled(false);

        jTextField_DungCuSX.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_DungCuSX.setEnabled(false);
        jTextField_DungCuSX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jTextField_VuKhi.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_VuKhi.setEnabled(false);
        jTextField_VuKhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_VuKhi.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_VuKhi.setText("Vũ Khí:");
        jLabel_VuKhi.setEnabled(false);

        jLabel_Ho.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Ho.setText("Hổ:");
        jLabel_Ho.setEnabled(false);

        jTextField_Ho.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_Ho.setEnabled(false);
        jTextField_Ho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jTextField_Soi.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_Soi.setEnabled(false);
        jTextField_Soi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_Soi.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Soi.setText("Chó Sói:");
        jLabel_Soi.setEnabled(false);

        jTextField_Gau.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_Gau.setEnabled(false);
        jTextField_Gau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel_Gau.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_Gau.setText("Gấu:");
        jLabel_Gau.setEnabled(false);

        jLabel_SLChuyenXeBaoVe.setForeground(new java.awt.Color(255, 0, 51));
        jLabel_SLChuyenXeBaoVe.setText("Số Lượng Chuyến Xe Bảo Vệ Được:");
        jLabel_SLChuyenXeBaoVe.setEnabled(false);

        jTextField_SLChuyenXeBaoVe.setForeground(new java.awt.Color(51, 0, 51));
        jTextField_SLChuyenXeBaoVe.setEnabled(false);
        jTextField_SLChuyenXeBaoVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Hãy nhập số lượng cho các vật phẩm bên dưới:");

        jLabel_SLChuyenXeVanChuyen.setForeground(new java.awt.Color(255, 0, 102));
        jLabel_SLChuyenXeVanChuyen.setText("Số Chuyến Xe Vận Chuyển Được:");
        jLabel_SLChuyenXeVanChuyen.setEnabled(false);

        jTextField_SLChuyenXeVanChuyen.setEnabled(false);
        jTextField_SLChuyenXeVanChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_HoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SLCayThuoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_SLCayThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel_VuKhi)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_VuKhi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel_LamNgoc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_LamNgoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_DungCuSX)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextField_DungCuSX, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_BichNgoc)
                                        .addComponent(jLabel_LinhChi))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_LinhChi)
                                        .addComponent(jTextField_BichNgoc, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel_NhanSam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_NhanSam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel_ThatTamLien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_ThatTamLien, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_SLChuyenXeVanChuyen)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_SLChuyenXeVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_SLChuyenXeBaoVe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_SLChuyenXeBaoVe, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addGap(504, 504, 504))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_ChungToc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_ChungToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(0, 423, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_MaTV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_MaTV)))
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_HongNgoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_HongNgoc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel_AoGiap)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_Soi)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_AoGiap, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Soi, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_KimCuong)
                                .addGap(26, 26, 26)
                                .addComponent(jTextField_KimCuong, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Gau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Gau, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_Ho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_GioiTinh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(191, 191, 191)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_NgaySinh)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel_HoTen)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(298, 298, 298)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox_NgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel_HaThuO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_HaThuO, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jButton_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel_Test, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaTV)
                    .addComponent(jTextField_MaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HoTen)
                    .addComponent(jTextField_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_GioiTinh)
                        .addComponent(jLabel_NgaySinh)
                        .addComponent(jComboBox_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_NgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_ChungToc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_ChungToc)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_SLCayThuoc)
                        .addComponent(jTextField_SLCayThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_SLChuyenXeVanChuyen)
                        .addComponent(jTextField_SLChuyenXeVanChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_LinhChi)
                    .addComponent(jTextField_LinhChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HaThuO)
                    .addComponent(jTextField_HaThuO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NhanSam)
                    .addComponent(jTextField_NhanSam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ThatTamLien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ThatTamLien))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_BichNgoc)
                    .addComponent(jTextField_BichNgoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_LamNgoc)
                    .addComponent(jTextField_LamNgoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_HongNgoc)
                    .addComponent(jTextField_HongNgoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_KimCuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_KimCuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DungCuSX)
                    .addComponent(jTextField_DungCuSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_VuKhi)
                    .addComponent(jTextField_VuKhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_AoGiap)
                    .addComponent(jTextField_AoGiap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Soi)
                    .addComponent(jTextField_Soi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Gau)
                    .addComponent(jTextField_Ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Ho)
                    .addComponent(jTextField_Gau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_SLChuyenXeBaoVe)
                    .addComponent(jTextField_SLChuyenXeBaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Nhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Test, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel_Test.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MaTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MaTVActionPerformed
        // TODO add your handling code here:Get_LamNgoc()
    }//GEN-LAST:event_jTextField_MaTVActionPerformed

    private void jComboBox_GTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GTActionPerformed
        
    }//GEN-LAST:event_jComboBox_GTActionPerformed

    private void jComboBox_ChungTocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ChungTocActionPerformed
    
    }//GEN-LAST:event_jComboBox_ChungTocActionPerformed

    private void jComboBox_ChungTocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ChungTocItemStateChanged
            if(evt.getStateChange() == ItemEvent.SELECTED){
                Object item = evt.getItem();
                String s = item.toString();
                switch(s)
                {  
                    case "Tinh Linh": 
                                    jComboBox_NgheNghiep.removeAllItems();
                                    jComboBox_NgheNghiep.addItem("Tìm Thuốc");
                                    jComboBox_NgheNghiep.addItem("Trồng Thuốc");
                                    jComboBox_NgheNghiep.validate();
                                    break;
                    case "Địa Tinh": 
                                    jComboBox_NgheNghiep.removeAllItems();
                                    jComboBox_NgheNghiep.addItem("Tìm Quặng");
                                    jComboBox_NgheNghiep.addItem("Tinh Chế Đồ");
                                    jComboBox_NgheNghiep.validate();
                                    break;
                    case "Người": 
                                    jComboBox_NgheNghiep.removeAllItems();
                                    jComboBox_NgheNghiep.addItem("Người Vận Chuyển");
                                    jComboBox_NgheNghiep.addItem("Lính Bảo An");
                                    jComboBox_NgheNghiep.validate();
                                    break;
                    default://
                        break;
                }
            }
    }//GEN-LAST:event_jComboBox_ChungTocItemStateChanged

    private void jComboBox_NgheNghiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NgheNghiepActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NgheNghiepActionPerformed

    private void jButton_NhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NhapActionPerformed
        
    }//GEN-LAST:event_jButton_NhapActionPerformed

    private void jButton_NhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_NhapMouseClicked
        Object o = jComboBox_NgheNghiep.getSelectedItem();
        String s = o.toString();
//        if(s.equalsIgnoreCase("Tìm Thuốc")){
//            g = new TinhLinhTimThuoc();
//            try {
//                g.Write();
//            } catch (SQLException | IOException ex) {
//                System.out.println("Loi ham Write: " + ex.getMessage());
//            }
//        }
        try{
            switch(s)
            {
                case "Tìm Thuốc":
                    g = new TinhLinhTimThuoc();
                    g.Write();
                    break;
                case "Trồng Thuốc":
                    g = new TinhLinhTrongThuoc();
                    g.Write();
                    break;
                case "Tìm Quặng":
                    g = new DiaTinhTimQuang();
                    g.Write();
                    break;
                case "Tinh Chế Đồ":
                    g = new DiaTinhTinhCheDo();
                    g.Write();
                    break;
                case "Người Vận Chuyển":
                    g = new NguoiVanChuyen();
                    g.Write();
                    break;
                case "Lính Bảo An":
                    g = new LinhBaoAn();
                    g.Write();
                    break;
            }
        }
        catch(SQLException | IOException  | SoLuongException ex) {
        }
    
    }//GEN-LAST:event_jButton_NhapMouseClicked

    private void jComboBox_NgheNghiepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_NgheNghiepItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            Object o = evt.getItem();
        String s = o.toString();
        switch(s)
        {
            case "Tìm Thuốc": Disable_ALL();
                jTextField_LinhChi.setEnabled(true);
                jTextField_HaThuO.setEnabled(true);
                jTextField_NhanSam.setEnabled(true);
                jTextField_ThatTamLien.setEnabled(true);
                jLabel_LinhChi.setEnabled(true);
                jLabel_HaThuO.setEnabled(true);
                jLabel_NhanSam.setEnabled(true);
                jLabel_ThatTamLien.setEnabled(true);
            
            break;
            case "Trồng Thuốc": Disable_ALL();
                jLabel_SLCayThuoc.setEnabled(true);
                jTextField_SLCayThuoc.setEnabled(true);
            break;
            case "Tìm Quặng": Disable_ALL();
                jLabel_BichNgoc.setEnabled(true);
                jLabel_LamNgoc.setEnabled(true);
                jLabel_HongNgoc.setEnabled(true);
                jLabel_KimCuong.setEnabled(true);
                jTextField_BichNgoc.setEnabled(true);
                jTextField_LamNgoc.setEnabled(true);
                jTextField_HongNgoc.setEnabled(true);
                jTextField_KimCuong.setEnabled(true);
                
                break;
            case "Tinh Chế Đồ": Disable_ALL();
                jLabel_DungCuSX.setEnabled(true);
                jLabel_VuKhi.setEnabled(true);
                jLabel_AoGiap.setEnabled(true);
                jTextField_DungCuSX.setEnabled(true);
                jTextField_VuKhi.setEnabled(true);
                jTextField_AoGiap.setEnabled(true);
                break;
            case "Người Vận Chuyển": Disable_ALL();
                jLabel_SLChuyenXeVanChuyen.setEnabled(true);
                jTextField_SLChuyenXeVanChuyen.setEnabled(true);
                break;
            case "Lính Bảo An": Disable_ALL();
                jLabel_SLChuyenXeBaoVe.setEnabled(true);
                jTextField_SLChuyenXeBaoVe.setEnabled(true);
                jLabel_Soi.setEnabled(true);
                jLabel_Gau.setEnabled(true);
                jLabel_Ho.setEnabled(true);
                jTextField_Soi.setEnabled(true);
                jTextField_Gau.setEnabled(true);
                jTextField_Ho.setEnabled(true);
                break;
            default://
                break;
        }
        }
    }//GEN-LAST:event_jComboBox_NgheNghiepItemStateChanged

    private void jTextField_KimCuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_KimCuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KimCuongActionPerformed

    private void jTextField_MaTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_MaTVMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jTextField_MaTVMouseClicked

    private void jTextField_HoTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_HoTenMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jTextField_HoTenMouseClicked

    private void jDateChooser_NgaySinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser_NgaySinhMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jDateChooser_NgaySinhMouseClicked

    private void jComboBox_GTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_GTMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jComboBox_GTMouseClicked

    private void jComboBox_ChungTocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_ChungTocMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jComboBox_ChungTocMouseClicked

    private void jComboBox_NgheNghiepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_NgheNghiepMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jComboBox_NgheNghiepMouseClicked

    private void jTextField_HoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_HoMouseClicked
        Set_NULL();
    }//GEN-LAST:event_jTextField_HoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Nhap;
    private javax.swing.JComboBox jComboBox_ChungToc;
    private javax.swing.JComboBox jComboBox_GT;
    private javax.swing.JComboBox jComboBox_NgheNghiep;
    private com.toedter.calendar.JDateChooser jDateChooser_NgaySinh;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_AoGiap;
    private javax.swing.JLabel jLabel_BichNgoc;
    private javax.swing.JLabel jLabel_ChungToc;
    private javax.swing.JLabel jLabel_DungCuSX;
    private javax.swing.JLabel jLabel_Gau;
    private javax.swing.JLabel jLabel_GioiTinh;
    private javax.swing.JLabel jLabel_HaThuO;
    private javax.swing.JLabel jLabel_Ho;
    private javax.swing.JLabel jLabel_HoTen;
    private javax.swing.JLabel jLabel_HongNgoc;
    private javax.swing.JLabel jLabel_KimCuong;
    private javax.swing.JLabel jLabel_LamNgoc;
    private javax.swing.JLabel jLabel_LinhChi;
    private javax.swing.JLabel jLabel_MaTV;
    private javax.swing.JLabel jLabel_NgaySinh;
    private javax.swing.JLabel jLabel_NhanSam;
    private javax.swing.JLabel jLabel_SLCayThuoc;
    private javax.swing.JLabel jLabel_SLChuyenXeBaoVe;
    private javax.swing.JLabel jLabel_SLChuyenXeVanChuyen;
    private javax.swing.JLabel jLabel_Soi;
    private javax.swing.JLabel jLabel_Test;
    private javax.swing.JLabel jLabel_ThatTamLien;
    private javax.swing.JLabel jLabel_VuKhi;
    private javax.swing.JTextField jTextField_AoGiap;
    private javax.swing.JTextField jTextField_BichNgoc;
    private javax.swing.JTextField jTextField_DungCuSX;
    private javax.swing.JTextField jTextField_Gau;
    private javax.swing.JTextField jTextField_HaThuO;
    private javax.swing.JTextField jTextField_Ho;
    private javax.swing.JTextField jTextField_HoTen;
    private javax.swing.JTextField jTextField_HongNgoc;
    private javax.swing.JTextField jTextField_KimCuong;
    private javax.swing.JTextField jTextField_LamNgoc;
    private javax.swing.JTextField jTextField_LinhChi;
    private javax.swing.JTextField jTextField_MaTV;
    private javax.swing.JTextField jTextField_NhanSam;
    private javax.swing.JTextField jTextField_SLCayThuoc;
    private javax.swing.JTextField jTextField_SLChuyenXeBaoVe;
    private javax.swing.JTextField jTextField_SLChuyenXeVanChuyen;
    private javax.swing.JTextField jTextField_Soi;
    private javax.swing.JTextField jTextField_ThatTamLien;
    private javax.swing.JTextField jTextField_VuKhi;
    // End of variables declaration//GEN-END:variables
    private GiaToc g;
    void Set_NULL(){
        jLabel_Test.setText("");
    }
    final void JDateChooser_Option(){
        JTextFieldDateEditor editor = (JTextFieldDateEditor) jDateChooser_NgaySinh.getDateEditor();
        editor.setEditable(false);
    }
    public String Get_JTextField_MaTV(){
        if(jTextField_MaTV.getText().isEmpty())
            return "";
        return jTextField_MaTV.getText();
    }
    public String Get_JTextField_HoTen(){
        if(jTextField_HoTen.getText().isEmpty())
            return "";
        return jTextField_HoTen.getText();
    }
    public String Get_JComboBox_GT(){
        return jComboBox_GT.getSelectedItem().toString();
    }
    public String Get_JDateChooser(){
        if(jDateChooser_NgaySinh.getDate() == null){
            return "";
        }
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        return f.format(jDateChooser_NgaySinh.getDate());
    }
    public String Get_ChungToc(){
        return jComboBox_ChungToc.getSelectedItem().toString();
    }
    public String Get_NgheNghiep(){
        return jComboBox_NgheNghiep.getSelectedItem().toString();
    }
    public int Get_LinhChi(){
        try{
        return Integer.parseInt(jTextField_LinhChi.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_HaThuO(){
        try{
        return Integer.parseInt(jTextField_HaThuO.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_NhanSam(){
        try{
        return Integer.parseInt(jTextField_NhanSam.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_ThatTamLien(){
        try{
        return Integer.parseInt(jTextField_ThatTamLien.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_CongCuSX(){
        try{
        return Integer.parseInt(jTextField_DungCuSX.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_VuKhi(){
        try{
        return Integer.parseInt(jTextField_VuKhi.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_AoGiap(){
        try{
        return Integer.parseInt(jTextField_AoGiap.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_Soi(){
        try{
        return Integer.parseInt(jTextField_Soi.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_Gau(){
        try{
        return Integer.parseInt(jTextField_Gau.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_Ho(){
        try{
        return Integer.parseInt(jTextField_Ho.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_BichNgoc(){
        try{
        return Integer.parseInt(jTextField_BichNgoc.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_LamNgoc(){
        try{
        return Integer.parseInt(jTextField_LamNgoc.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_HongNgoc(){
        try{
        return Integer.parseInt(jTextField_HongNgoc.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_KimCuong(){
        try{
        return Integer.parseInt(jTextField_KimCuong.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_SLCayThuoc(){
        try{
        return Integer.parseInt(jTextField_SLCayThuoc.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_SLChuyenXeBaoVe(){
        try{
        return Integer.parseInt(jTextField_SLChuyenXeBaoVe.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public int Get_SLChuyenXeVanChuyen(){
        try{
        return Integer.parseInt(jTextField_SLChuyenXeVanChuyen.getText());
        }
        catch(NumberFormatException e){
        }
        return -1;
    }
    public void Set_Jlabel_Test(String str){
        jLabel_Test.setText(str);
    }
    public void Disable_ALL(){
        jLabel_LinhChi.setEnabled(false);
        jLabel_HaThuO.setEnabled(false);
        jLabel_NhanSam.setEnabled(false);
        jLabel_ThatTamLien.setEnabled(false);
        jTextField_LinhChi.setEnabled(false);
        jTextField_LinhChi.setText(null);
        jTextField_HaThuO.setEnabled(false);
        jTextField_HaThuO.setText(null);
        jTextField_NhanSam.setEnabled(false);
        jTextField_NhanSam.setText(null);
        jTextField_ThatTamLien.setEnabled(false);
        jTextField_ThatTamLien.setText(null);
        //
        jLabel_BichNgoc.setEnabled(false);
        jLabel_LamNgoc.setEnabled(false);
        jLabel_HongNgoc.setEnabled(false);
        jLabel_KimCuong.setEnabled(false);
        jTextField_BichNgoc.setEnabled(false);
        jTextField_BichNgoc.setText(null);
        jTextField_LamNgoc.setEnabled(false);
        jTextField_LamNgoc.setText(null);
        jTextField_HongNgoc.setEnabled(false);
        jTextField_HongNgoc.setText(null);
        jTextField_KimCuong.setEnabled(false);
        jTextField_KimCuong.setText(null);
        //
        jLabel_DungCuSX.setEnabled(false);
        jLabel_VuKhi.setEnabled(false);
        jLabel_AoGiap.setEnabled(false);
        jTextField_DungCuSX.setEnabled(false);
        jTextField_DungCuSX.setText(null);
        jTextField_VuKhi.setEnabled(false);
        jTextField_VuKhi.setText(null);
        jTextField_AoGiap.setEnabled(false);
        jTextField_AoGiap.setText(null);
        //
        jLabel_SLChuyenXeBaoVe.setEnabled(false);
        jTextField_SLChuyenXeBaoVe.setEnabled(false);
        jLabel_Soi.setEnabled(false);
        jLabel_Gau.setEnabled(false);
        jLabel_Ho.setEnabled(false);
        jTextField_Soi.setEnabled(false);
        jTextField_Soi.setText(null);
        jTextField_Gau.setEnabled(false);
        jTextField_Gau.setText(null);
        jTextField_Ho.setEnabled(false);
        jTextField_Ho.setText(null);
        //
        jLabel_SLCayThuoc.setEnabled(false);
        jTextField_SLCayThuoc.setEnabled(false);
        jTextField_SLCayThuoc.setText(null);
        //
        jLabel_SLChuyenXeVanChuyen.setEnabled(false);
        jTextField_SLChuyenXeVanChuyen.setEnabled(false);
        jTextField_SLChuyenXeVanChuyen.setText(null);
    }
    }
