/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package csdl;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ANHMATTROI
 */
public class SinhVien extends javax.swing.JFrame
{
    private int i;// lưu chỉ số hàng hiện tại
    private KetNoi kn; //biến lớp kết nối
    private ResultSet bang;//chứa 1 dữ liệu sau khi chạy lenh truy van sql
    private TableModel table_model; //để tạo cột, thêm hàng bằng lệnh
    private ResultSetMetaData info_table; //chứa thông tin của bảng kết quả trả về như số hàng của bảng ...
    private DefaultTableModel model;
    private String chuoi;
    private boolean ketqua; //xem kết quả các câu lệnh truy vấn có thành công hay không
    
    public SinhVien() throws ClassNotFoundException, SQLException //hàm khởi tạo tải các dữ liệu khi form khởi động
    {
        initComponents();
        i = 0;
        kn = new KetNoi(); //cấp phát bộ nhớ cho lớp kết nối
        if(!kn.Mo())//nếu kết nối không thành công hiện thị thông báo và thoát chương trình
        {
            JOptionPane.showMessageDialog(null, "Lỗi kết nối");// đây là messagebox ở trong window
            System.exit(0); // lệnh thoát chương trình
        }
        table_model = new DefaultTableModel(null, ChenCot());
        tbl_sinhvien.setModel(table_model);
        ChenHang();
        if(tbl_sinhvien.getRowCount() > 0) GanLenTB();
        tbl_sinhvien.setShowGrid(true);
        tbl_sinhvien.changeSelection(0, 0, false, false);
        tbten.requestFocus(); //hiện con chooutj trong textfield họ tên sinh viên
    }
    
    //tải tên các cột cho biến tbnhanvien: là bảng kéo thả vào đó
    private Object[] ChenCot()
    {
        String[] cac_cot = {"Mã sinh viên", "Họ và tên", "Ngày sinh", "Giới tính", "Địa chỉ"};
        return cac_cot;
    }
    
    //tai danh sach nhân viên đã có trong cơ sở dữ liệu
    private void ChenHang() throws SQLException
    {
        bang = kn.LayDL("select * from SinhVien"); //chạy lệnh truy vận kết quả trả về một bảng dữ liệu
        boolean kq = bang.next();
        String[] hang;
        model = (DefaultTableModel)tbl_sinhvien.getModel();
        if(kq)
        {
            int i = 0;
            while(kq)
            {
                hang = new String[5];
                hang[0] = bang.getString(1);
                hang[1] = bang.getString(2);
                hang[2] = bang.getString(3);
                hang[3] = bang.getString(4);
                hang[4] = bang.getString(5);
                i++;
                model.addRow(hang);
                kq = bang.next();
            }
        }
        bang.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        sroltablel = new javax.swing.JScrollPane();
        tbl_sinhvien = new javax.swing.JTable();
        btthem = new javax.swing.JButton();
        btluu = new javax.swing.JButton();
        btxoa = new javax.swing.JButton();
        tbtimkiem = new javax.swing.JTextField();
        bttimkiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tbma = new javax.swing.JTextField();
        tbten = new javax.swing.JTextField();
        tbngaysinh = new javax.swing.JTextField();
        tbgioitinh = new javax.swing.JTextField();
        tbdiachi = new javax.swing.JTextField();
        bttruoc = new javax.swing.JButton();
        btsau = new javax.swing.JButton();
        btdau_cuoi = new javax.swing.JButton();
        bttiep = new javax.swing.JButton();
        bttailai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí sinh viên");
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pn.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sinhvien.setAutoCreateRowSorter(true);
        tbl_sinhvien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_sinhvien.setCellSelectionEnabled(true);
        tbl_sinhvien.setEditingColumn(0);
        tbl_sinhvien.setEditingRow(0);
        tbl_sinhvien.setGridColor(new java.awt.Color(204, 204, 204));
        tbl_sinhvien.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tbl_sinhvien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_sinhvien.getTableHeader().setReorderingAllowed(false);
        tbl_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sinhvienMouseClicked(evt);
            }
        });
        sroltablel.setViewportView(tbl_sinhvien);

        btthem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btthem.setText("Thêm");
        btthem.setBorderPainted(false);
        btthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btthemMouseClicked(evt);
            }
        });

        btluu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btluu.setText("Lưu");
        btluu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btluuMouseClicked(evt);
            }
        });

        btxoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btxoa.setText("Xóa");
        btxoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btxoaMouseClicked(evt);
            }
        });

        tbtimkiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bttimkiem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bttimkiem.setText("Tìm kiếm");
        bttimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttimkiemMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã sinh viên");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Họ và tên");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ngày sinh");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Giới tính");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Địa chỉ");

        tbma.setEditable(false);
        tbma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tbten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tbngaysinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tbgioitinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tbdiachi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bttruoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bttruoc.setText("<<");
        bttruoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttruocMouseClicked(evt);
            }
        });

        btsau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btsau.setText(">>");
        btsau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsauMouseClicked(evt);
            }
        });

        btdau_cuoi.setBackground(new java.awt.Color(204, 204, 204));
        btdau_cuoi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btdau_cuoi.setText("<=>");
        btdau_cuoi.setBorderPainted(false);
        btdau_cuoi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btdau_cuoi.setFocusPainted(false);
        btdau_cuoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdau_cuoiMouseClicked(evt);
            }
        });

        bttiep.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bttiep.setText("Tiếp theo");
        bttiep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttiepMouseClicked(evt);
            }
        });

        bttailai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bttailai.setText("Tải lại");
        bttailai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttailaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sroltablel)
                    .addGroup(pnLayout.createSequentialGroup()
                        .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tbgioitinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                    .addComponent(tbngaysinh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbten, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbma, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(tbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttimkiem))
                            .addGroup(pnLayout.createSequentialGroup()
                                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnLayout.createSequentialGroup()
                                        .addGap(225, 225, 225)
                                        .addComponent(bttiep)
                                        .addGap(23, 23, 23)
                                        .addComponent(btluu)
                                        .addGap(18, 18, 18)
                                        .addComponent(btxoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(bttailai)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnLayout.createSequentialGroup()
                        .addComponent(btdau_cuoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttruoc)
                        .addGap(18, 18, 18)
                        .addComponent(btsau)
                        .addGap(18, 18, 18)
                        .addComponent(btthem)
                        .addGap(458, 458, 458)))
                .addContainerGap())
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttimkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btthem)
                    .addComponent(btluu)
                    .addComponent(btxoa)
                    .addComponent(bttruoc)
                    .addComponent(btsau)
                    .addComponent(btdau_cuoi)
                    .addComponent(bttiep)
                    .addComponent(bttailai))
                .addGap(18, 18, 18)
                .addComponent(sroltablel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean KiemTraDuLieuNhapVao()
    {
        //kiểm tra xem có nhập dữ liệu không
        if(tbma.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã sinh viên");
            tbma.requestFocus();
            return false;
        }
        
        if(tbten.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập họ và tên sinh viên");
            tbten.requestFocus();
            return false;
        }
        
        if(tbngaysinh.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày sinh");
            tbngaysinh.requestFocus();
            return false;
        }
        
        if(tbgioitinh.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập giới tính");
            tbgioitinh.requestFocus();
            return false;
        }
        
        if(tbdiachi.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ");
            tbdiachi.requestFocus();
            return false;
        }
        
        //kiểm tra xem nhập dữ liệu có đúng không
        try
        {
            bang = kn.LayDL("select MaSV from SinhVien where MaSV = '" + tbma.getText() + "'");
            if(bang.next())
            {
                JOptionPane.showMessageDialog(null, "Mã sinh viên đã tồn tại");
                tbma.setEditable(true);
                tbma.requestFocus();
                return false;
            }
        }
        catch(SQLException ex)
        {
            
        }
        return true;
    }
    
    private void btthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btthemMouseClicked
        // TODO add your handling code here:
        ketqua = KiemTraDuLieuNhapVao();
        if(!ketqua) return;
        String[] hang = new String[5];
        model = (DefaultTableModel)tbl_sinhvien.getModel();
        hang[0] = tbma.getText();
        hang[1] = tbten.getText();
        hang[2] = tbngaysinh.getText();
        hang[3] = tbgioitinh.getText();
        hang[4] = tbdiachi.getText();
        chuoi = "insert into SinhVien values('"
                + hang[0] + "', N'"
                + hang[1] + "', '"
                + hang[2] + "', N'"
                + hang[3] + "', N'"
                + hang[4] + "')";
        ketqua = kn.CapNhat(chuoi);
        if(!ketqua)
        {
            JOptionPane.showMessageDialog(null, "Có lỗi");
            tbma.requestFocus();
            return;
        }
        model.addRow(hang);
        tbma.setEditable(false);
    }//GEN-LAST:event_btthemMouseClicked

    private void btxoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btxoaMouseClicked
        if(i < 0 || i > tbl_sinhvien.getRowCount()) return;
        int yes, no;
        yes = JOptionPane.YES_OPTION;
        no = JOptionPane.NO_OPTION;
        if(yes == JOptionPane.showConfirmDialog(null, "Bạn muốn xóa sinh viên này ?", "Xác nhân", yes))
        {
            chuoi = "delete from SinhVien where MaSV = '" + tbma.getText() + "'";
            ketqua = kn.CapNhat(chuoi);
            if(!ketqua)
            {
                JOptionPane.showMessageDialog(null, "Lỗi không xóa được");
                return;
            }
        }
        else return;
        model = (DefaultTableModel)tbl_sinhvien.getModel();
        model.removeRow(i);
        if(i >= tbl_sinhvien.getRowCount()) i--;
        if(i > -1)
        {
            
            tbl_sinhvien.changeSelection(i, 0, false, false);
            GanLenTB();
        }
    }//GEN-LAST:event_btxoaMouseClicked

    private void GanLenTB()
    {
        if(tbl_sinhvien.getValueAt(i, 0) != null) tbma.setText(tbl_sinhvien.getValueAt(i, 0).toString());
        else tbma.setText("");
        
        if(tbl_sinhvien.getValueAt(i, 1) != null) tbten.setText(tbl_sinhvien.getValueAt(i, 1).toString());
        else tbten.setText("");
        
        if(tbl_sinhvien.getValueAt(i, 2) != null) tbngaysinh.setText(tbl_sinhvien.getValueAt(i, 2).toString());
        else tbngaysinh.setText("");
        
        if(tbl_sinhvien.getValueAt(i, 3) != null) tbgioitinh.setText(tbl_sinhvien.getValueAt(i, 3).toString());
        else tbgioitinh.setText("");
        
        if(tbl_sinhvien.getValueAt(i, 4) != null) tbdiachi.setText(tbl_sinhvien.getValueAt(i, 4).toString());
        else tbdiachi.setText("");
    }
    
    private void tbl_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sinhvienMouseClicked
        // TODO add your handling code here:
        i = tbl_sinhvien.getSelectedRow();
        if(i < 0 || i > tbl_sinhvien.getRowCount()) return;
        GanLenTB();
    }//GEN-LAST:event_tbl_sinhvienMouseClicked

    private void btluuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btluuMouseClicked
        // TODO add your handling code here:
        if(i < 0 || i > tbl_sinhvien.getRowCount()) return;
        int yes, no;
        yes = JOptionPane.YES_OPTION;
        no = JOptionPane.NO_OPTION;
        if(yes == JOptionPane.showConfirmDialog(null, "Sửa thông tin sinh viên này ?", "Xác nhân", yes))
        {
            try
            {
                bang = kn.LayDL("select MaSV from SinhVien where MaSV = '" + tbma.getText() + "'");
                if(!bang.next())
                {
                    JOptionPane.showMessageDialog(null, "Mã sinh viên không tồn tại");
                    tbma.setEditable(true);
                    tbma.requestFocus();
                    return;
                }
            }
            catch(SQLException ex)
            {

            }
            chuoi = "update SinhVien set "
                    + "HoTen = N'" + tbten.getText() + "', "
                    + "NgaySinh = '" + tbngaysinh.getText() + "', "
                    + "GioiTinh = N'" + tbgioitinh.getText() + "', "
                    + "DiaChi = N'" + tbdiachi.getText() + "' where MaSV = '" + tbma.getText() + "'";
            ketqua = kn.CapNhat(chuoi);
            if(!ketqua)
            {
                JOptionPane.showMessageDialog(null, "Lỗi không sửa được");
                return;
            }
            String[] hang = new String[5];
            hang[0] = tbma.getText();
            hang[1] = tbten.getText();
            hang[2] = tbngaysinh.getText();
            hang[3] = tbgioitinh.getText();
            hang[4] = tbdiachi.getText();
            tbl_sinhvien.setValueAt(hang[0], i, 0);
            tbl_sinhvien.setValueAt(hang[1], i, 1);
            tbl_sinhvien.setValueAt(hang[2], i, 2);
            tbl_sinhvien.setValueAt(hang[3], i, 3);
            tbl_sinhvien.setValueAt(hang[4], i, 4);
        }
    }//GEN-LAST:event_btluuMouseClicked

    private void bttiepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttiepMouseClicked
        // TODO add your handling code here:
        tbma.setText("");
        tbten.setText("");
        tbngaysinh.setText("");
        tbgioitinh.setText("");
        tbdiachi.setText("");
        tbma.setEditable(true);
        tbma.requestFocus();
    }//GEN-LAST:event_bttiepMouseClicked

    private void bttailaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttailaiMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel)tbl_sinhvien.getModel();
        int j = 0;
        while(j < tbl_sinhvien.getRowCount())
        {
            model.removeRow(j);
        }
        try
        {
            ChenHang();
            if(i > -1 && i < tbl_sinhvien.getRowCount())
            {
                i = 0;
                tbl_sinhvien.changeSelection(i, 0, false, false);
                GanLenTB();
            }
        }
        catch(SQLException ex)
        {
            
        }
    }//GEN-LAST:event_bttailaiMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        kn.DongKetNoi();
    }//GEN-LAST:event_formWindowClosing

    private void btsauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsauMouseClicked
        // TODO add your handling code here:
        if(i > -1 && i < tbl_sinhvien.getRowCount())
        {
            i++;
            if(i >= tbl_sinhvien.getRowCount()) i = tbl_sinhvien.getRowCount() - 1;
            tbl_sinhvien.changeSelection(i, 0, false, false);
            GanLenTB();
        }
    }//GEN-LAST:event_btsauMouseClicked

    private void bttruocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttruocMouseClicked
        // TODO add your handling code here:
        if(i > -1 && i < tbl_sinhvien.getRowCount())
        {
            i--;
            if(i < 0) i = 0;
            tbl_sinhvien.changeSelection(i, 0, false, false);
            GanLenTB();
        }
    }//GEN-LAST:event_bttruocMouseClicked

    private void btdau_cuoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdau_cuoiMouseClicked
        // TODO add your handling code here:
        if(i > -1 && i < tbl_sinhvien.getRowCount())
        {
            if(i > 0) 
            {
                i = 0;
                tbl_sinhvien.changeSelection(i, 0, false, false);
                GanLenTB();
                return;
            }
            if(i < tbl_sinhvien.getRowCount() - 1) 
            {
                i = tbl_sinhvien.getRowCount() - 1;
                tbl_sinhvien.changeSelection(i, 0, false, false);
                GanLenTB();
                return;
            }
        }
    }//GEN-LAST:event_btdau_cuoiMouseClicked

    private void bttimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttimkiemMouseClicked
        // TODO add your handling code here:
        i = 0;
        model = (DefaultTableModel)tbl_sinhvien.getModel();
        while(tbl_sinhvien.getRowCount() > 0)
        {
            model.removeRow(i);
        }
        chuoi = "select * from SinhVien where MaSV like '%" + tbtimkiem.getText() + "%' or HoTen like N'%" + tbtimkiem.getText() + "%'";
        bang = kn.LayDL(chuoi);
        String[] hang;
        try 
        {
            ketqua = bang.next();
            while(ketqua)
            {
                hang = new String[5];
                hang[0] = bang.getString(1);
                hang[1] = bang.getString(2);
                hang[2] = bang.getString(3);
                hang[3] = bang.getString(4);
                hang[4] = bang.getString(5);
                model.addRow(hang);
                ketqua = bang.next();
            }
            if(tbl_sinhvien.getRowCount() > 0)
            {
                tbl_sinhvien.changeSelection(i, 0, false, false);
                GanLenTB();
            }
        } 
        catch (SQLException ex) 
        {
            
        }
    }//GEN-LAST:event_bttimkiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                try {
                    new SinhVien().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SinhVien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SinhVien.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdau_cuoi;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btsau;
    private javax.swing.JButton bttailai;
    private javax.swing.JButton btthem;
    private javax.swing.JButton bttiep;
    private javax.swing.JButton bttimkiem;
    private javax.swing.JButton bttruoc;
    private javax.swing.JButton btxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pn;
    private javax.swing.JScrollPane sroltablel;
    private javax.swing.JTextField tbdiachi;
    private javax.swing.JTextField tbgioitinh;
    private javax.swing.JTable tbl_sinhvien;
    private javax.swing.JTextField tbma;
    private javax.swing.JTextField tbngaysinh;
    private javax.swing.JTextField tbten;
    private javax.swing.JTextField tbtimkiem;
    // End of variables declaration//GEN-END:variables
}
